### ISSUE TITLE
json is no longer generated

### ISSUE THREAD

**Issue by sTmp-7** [Xzandro/sw-exporter#361] opened 2021-01-19 02:30 UTC
Today, for no reason the exporter stopped working. Came here to see if it was some issue cause of last upgrade in game (01/16), but it seems no one has the same problem. I saw there was a new version (.37) so a upgraded, but still it didn't work properly.

Does someone has experienced something similar or would help me to solve this problem?

**Comment by Xzandro** [comment] 2021-01-19 02:35
Duplicate of #359

**Closed by Xzandro** 2021-01-19 02:35 UTC
