### ISSUE TITLE
Exception with 'install version', pinned portable version doesn't launch

### ISSUE THREAD

**Issue by mightormagic** [Xzandro/sw-exporter#215] opened 2019-05-24 01:39 UTC
after installing the 0.0.25 install version in win10, everytime i launch the game, it gives this error

![image](https://user-images.githubusercontent.com/42580452/58296780-165f5b00-7da3-11e9-80a4-fd30e246b45b.png)

Using the portable version works, but if i pin it to the task bar in win10, then later launch it again, it wont launch as if i didn't click it.
If i click the exe in the folder structure, it launches fine.

**Comment by Xzandro** [comment] 2019-05-24 11:28
Hey, sadly I can't reproduce this error. Setup works totally fine for me. The behavior of the portable version is normal, its basically a temporarey version of SWEX and can be deleted at any time, since it will be installed in the temp folder.
Do you have any weird SWEX settings or anything else different than die standart installation?

**Closed** 2019-07-08 00:11 UTC
