### ISSUE TITLE
Cert for version .30 not working on latest iOS

### ISSUE THREAD

**Issue by Glemoyn** [Xzandro/sw-exporter#286] opened 2019-10-03 10:02 UTC
When trying to log on to SW  while using SWEX Proxy, iOS version 13.1.2 seems to ignore the Cert, even if it is set to trusted and installed

**To Reproduce**
1. Update iOS  to 13.1.2
2. Open up SWEX Version .30 (issue also happens with version .27)
2. Set up SWEX Proxy like normal. (getting Cert, installing & trusting Cert, ect...)
3. Attempt to start SW with proxy running.
4. Get error message " Failed to connect with the network. Please try again later.(S:9)"

**Expected behavior**
It was expected to open into summoners war like normal, downloading the .JSON.

**Screenshots**
<img width="667" alt="Screenshot 2019-10-03 at 02 45 06" src="https://user-images.githubusercontent.com/49622844/66117166-de55f900-e588-11e9-85ba-181f3e4e75fe.png">
<img width="375" alt="Screenshot 2019-10-03 at 02 43 31" src="https://user-images.githubusercontent.com/49622844/66117175-e3b34380-e588-11e9-8923-87fa032be6e4.png">

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version: 18362.356

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - iOS: 13.1.2

**Additional context**
I noticed this error is the same one you get if you forget to trust the cert in iOS/General/About/Certificate trust settings.
I did make sure all the data is input correctly ( port and server), tested it on multiple wifi networks, and even reinstalled the cert from scratch using the latest version of SWEX (.30).

Edit: 10/03 03:06: I tried forgeting the saved wifi network and reconnecting to it (with the set up proxy information) just in case the update messed with the saved wifi profile. This did not fix the issue (which I didnt expect it to tbh)

**Comment by Xzandro** [comment] 2019-10-03 18:57
Duplicate of #283

**Closed by Xzandro** 2019-10-03 18:57 UTC
