### ISSUE TITLE
exporter not creating json files

### ISSUE THREAD

**Issue by asteriuszzz** [Xzandro/sw-exporter#360] opened 2021-01-19 00:38 UTC
Im using exporter for a while now but this is my first time encountering this kind of bug ( I think) 
The exporter is working though Im able to use sw without any connection issues, but the exporter it self started not creating json files, I tried reinstalling exporter and bignox several times now I even installed lower vertions but it still doesnt create json files. please help

**Comment by Xzandro** [comment] 2021-01-19 01:14
Duplicate of #359

**Closed by Xzandro** 2021-01-19 01:14 UTC
