### ISSUE TITLE
[BUG] Can't connect to the proxy. NOT WORKING

### ISSUE THREAD

**Issue by makseeh** [Xzandro/sw-exporter#268] opened 2019-09-01 15:08 UTC
Proxy app not working. After launching the app & configuring my Galaxy S7 proxy I cannot connect to the game. SW error - "Failed to connect with the network. Please try again later.(S:9)"
When I try to use SWProxy my network works fine but the app is not reading SW and isn't giving me JSON file so I tried this app. Can you fix the issue? Or tell me if I'm doing something wrong? I've always used SWProxy but because it's not creating JSON file I wanted to try this and hoped for a solution. And I might add that for some reason, I can't connect to the game without SWProxy or VPN. My main network is blocked for some reason by Summoners War ...

Samsung Galaxy S7 SM-G930F
Using on Android 8.0.0
PC - Windows 7 Ultimate

If you need more info you can add me on LINE - makseeh

**Comment by drequeceler** [comment] 2019-09-01 15:19
same error here

![Screenshot_1](https://user-images.githubusercontent.com/1971658/64078577-cc93e400-ccb2-11e9-982c-4183a18eddad.jpg)

**Comment by Xzandro** [comment] 2019-09-01 15:34
Please read this thread: https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/

Duplicate of #243

**Closed by Xzandro** 2019-09-01 15:34 UTC
