### ISSUE TITLE
[BUG] Was working fine until a few days ago with my iphone, but recently i'm unable to see any log activity, I know the proxy is working since i can still play through the proxy wich swex started.  I don't see any recent issue activity, am I the only one with the issue?  :)  thanks!

### ISSUE THREAD

**Issue by Aljehandro** [Xzandro/sw-exporter#364] opened 2021-01-20 01:15 UTC
**Please don't report issues that are not relevant to SWEX. Especially now that are more steps involved which you can read on [reddit](https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/). To get more information, join the [Discord](https://discord.gg/JMBSZRA).**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- Version

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Xzandro** [comment] 2021-01-20 01:56
I would always recommend to look into the closed issues as well.

Duplicate of #359

**Closed by Xzandro** 2021-01-20 01:56 UTC
