### ISSUE TITLE
Summoners war exporter not showing "Found API Command"

### ISSUE THREAD

**Issue by HamzaLodhi** [Xzandro/sw-exporter#248] opened 2019-08-23 04:11 UTC
Usually it shows "Found API Command " when i see other people use it on youtube. However when I use it the games loads normally but Summoners War Exporter does not show any information when the game loads. 

Here are the list of things that I have already tried:
1. Turn off my antivirus's firewall (Mcafee)
2. Uninstalled my antivirus (Mcafee) along with other files related to Mcafee. (Reinstalled it later)
3. Turn off Windows Firewall
4. Run as administrator
5. Changed port number from 8080 to other numbers like 8086 etc.
6. Tried to Use Summoners War Proxy and faced the exact same difficulty (SWProxy not showing that it received information)

I checked the folder where the files are supposed to transfer to, however they are empty. I have tried downloading some different versions for the last 3 days but there is no luck. I would really appreciate some help.
I am starting to lose hope and resorting to enter my 924 runes manually.

**Comment by startiik** [comment] 2019-08-23 10:59
Same nothing seems to work for me. not 28 neither 27... with the root cert installed

**Comment by Xzandro** [comment] 2019-08-23 13:40
Duplicate of #243

**Closed by Xzandro** 2019-08-23 13:40 UTC
