### ISSUE TITLE
SWEX 0.0.28 not working because of HTTPS

### ISSUE THREAD

**Issue by Hordil** [Xzandro/sw-exporter#243] opened 2019-08-21 08:58 UTC
Aaand there we go again..

**Comment by My-Fellow-Dude** [comment] 2019-08-21 09:14
Prolly same here

**Comment by ianchudson** [comment] 2019-08-21 10:18
Yep, seems to have stopped working in the last 6 hours.

**Comment by Hordil** [comment] 2019-08-21 10:22
0.27 works, use it on my computer + 3 android devices - even version 8+, and got no problems.. hmmm. :-)

**Comment by My-Fellow-Dude** [comment] 2019-08-21 12:19
Hmmm. After switching back to 0.27, all I get is "Failed to connect with network." error message. :-|

**Comment by Xzandro** [comment] 2019-08-21 13:18
Yes, HTTPS is back again. v0.0.27 should work still with the additional steps provided in the reddit hread here:  https://www.reddit.com/r/summonerswar/comments/cnwaq5/swex_0027_attempt_to_restore_export_functionality/

Its not necessarly a bug or issue with SWEX, so to avoid confusion I leave it open for now.

**Comment by ianchudson** [comment] 2019-08-21 16:52
> Yep, seems to have stopped working in the last 6 hours.

Confirmed that 0.0.27 works on latest iOS still after installing root cert.

**Comment by hyudryu** [comment] 2019-08-22 10:23
> > Yep, seems to have stopped working in the last 6 hours.
> 
> Confirmed that 0.0.27 works on latest iOS still after installing root cert.

How did you manage to get it to work? I'm still struggling right now lol.

Long story short, I updated to the newest IOS 12.4 and SWExporter stopped picking things up. My ipad still works fine on SWExporter 0.0.24 as we speak though :P 

I am currently running SWExporter 0.0.27, and downloaded the ca.pem certificate file. I then emailed the certificate file to myself, and opened the email via my iPhone. Went to Settings > General > Profiles & Device Management >Install NodeMITMProxyCA, and configured the wifi IP and stuff as usual. However, my iPhone is not connecting to the internet anymore, which means it's either not reaching the proxy, or the proxy isn't passing stuff through.

**Comment by Playa29** [comment] 2019-08-22 10:28
> > > Yep, seems to have stopped working in the last 6 hours.
> > 
> > 
> > Confirmed that 0.0.27 works on latest iOS still after installing root cert.
> 
> How did you manage to get it to work? I'm still struggling right now lol.
> 
> Long story short, I updated to the newest IOS 12.4 and SWExporter stopped picking things up. My ipad still works fine on SWExporter 0.0.24 as we speak though :P
> 
> I just downloaded SWExporter 0.0.27, and grabbed the ca.pem certificate file. I then emailed the certificate file to myself, and opened the email via my iPhone. Went to Settings > General > Profiles & Device Management >Install NodeMITMProxyCA, and configured the wifi IP and stuff as usual. However, my iPhone is not connecting to the internet anymore, which means it's either not reaching the proxy, or the proxy isn't passing stuff through.

Hey, you have to trust the installed certificate in the settings, to make it work. https://support.apple.com/en-us/HT204477

**Comment by hyudryu** [comment] 2019-08-22 10:32
> Hey, you have to trust the installed certificate in the settings, to make it work. https://support.apple.com/en-us/HT204477

You are a lifesaver :) Thank you so much for that

**Comment by DavidSaniez** [comment] 2019-08-22 11:28
I did all steps but not working on android 9. Failed to connect in game...

**Comment by duchoang** [comment] 2019-08-22 11:46
> the installed certificate in the settings, to make it work. https://support.apple.com/en-us/HT204477

thanks a lot for this tip, followed this and worked on ios

**Comment by Playa29** [comment] 2019-08-22 12:00
> I did all steps but not working on android 9. Failed to connect in game...

This will NOT work for Android 7+ and probably never will, because as default apps won't trust self signed user certs

So, your Android Version is to high.

**Comment by DavidSaniez** [comment] 2019-08-22 12:05
> 
> 
> > I did all steps but not working on android 9. Failed to connect in game...
> 
> "This will NOT work for Android 7+ and probably never will, because as default apps won't trust self signed user certs"
> 
> So, your Android Version is to high.

Oups, sorry didn't see it. My bad.

**Comment by Revark** [comment] 2019-08-22 17:31
Any word on possible fix or work around for later android users?

**Comment by PeteAndersen** [comment] 2019-08-22 17:35
No, it's impossible due to android security policies. Read up here for
technical details
https://www.charlesproxy.com/documentation/using-charles/ssl-certificates/

**Comment by siwakorn9** [comment] 2019-08-23 12:58
> > > Yep, seems to have stopped working in the last 6 hours.
> > 
> > 
> > Confirmed that 0.0.27 works on latest iOS still after installing root cert.
> 
> How did you manage to get it to work? I'm still struggling right now lol.
> 
> Long story short, I updated to the newest IOS 12.4 and SWExporter stopped picking things up. My ipad still works fine on SWExporter 0.0.24 as we speak though :P
> 
> I just downloaded SWExporter 0.0.27, and grabbed the ca.pem certificate file. I then emailed the certificate file to myself, and opened the email via my iPhone. Went to Settings > General > Profiles & Device Management >Install NodeMITMProxyCA, and configured the wifi IP and stuff as usual. However, my iPhone is not connecting to the internet anymore, which means it's either not reaching the proxy, or the proxy isn't passing stuff through.

Hey folks, my apologize but I'm really new here.
How did you manage to install that I can't find Profiles&Device Management on my iPhone at all.
Sorry if this is might be stupid question....

**Comment by darbyjack** [comment] 2019-08-23 16:12
> > > > Yep, seems to have stopped working in the last 6 hours.
> > > 
> > > 
> > > Confirmed that 0.0.27 works on latest iOS still after installing root cert.
> > 
> > 
> > How did you manage to get it to work? I'm still struggling right now lol.
> > Long story short, I updated to the newest IOS 12.4 and SWExporter stopped picking things up. My ipad still works fine on SWExporter 0.0.24 as we speak though :P
> > I just downloaded SWExporter 0.0.27, and grabbed the ca.pem certificate file. I then emailed the certificate file to myself, and opened the email via my iPhone. Went to Settings > General > Profiles & Device Management >Install NodeMITMProxyCA, and configured the wifi IP and stuff as usual. However, my iPhone is not connecting to the internet anymore, which means it's either not reaching the proxy, or the proxy isn't passing stuff through.
> 
> Hey folks, my apologize but I'm really new here.
> How did you manage to install that I can't find Profiles&Device Management on my iPhone at all.
> Sorry if this is might be stupid question....

If you type in "cert" into the settings bar, it will come up!

**Comment by janeric123** [comment] 2019-08-23 18:53
so android/androidbased systems wont be able to use sw runeoptimizer/farm/exporter anymore till the end of time? Or is this just a temporal thing where its possible to be solved in another way? Because i think this would probably effect sw endgame quite a lot since I and basicly all other g2/3 ppl i ever talked to use these tools since its basicly impossible finding the best rune combination with 1200+ runes by urself

**Comment by darbyjack** [comment] 2019-08-23 18:55
> so android/androidbased systems wont be able to use sw runeoptimizer/farm/exporter anymore till the end of time? Or is this just a temporal thing where its possible to be solved in another way? Because i think this would probably effect sw endgame quite a lot since I and basicly all other g2/3 ppl i ever talked to use these tools since its basicly impossible finding the best rune combination with 1200+ runes by urself

This is mainly a temp thing until there's a workaround or until there is a fever of https again. I had issues with Android myself so I found an old iPad on IOS 9 and was able to continue using SWEX this morning.

**Comment by janeric123** [comment] 2019-08-23 18:56
ahhh ok thats nice to hear!
and thanks for the quick reply ^^

**Comment by darbyjack** [comment] 2019-08-23 18:58
> ahhh ok thats nice to hear!
> and thanks for the quick reply ^^

A TLDR of why it doesn't work on Android is that it's a security thing with certs. I tried it on my Galaxy S10+ and no bueno, even installing certs and whatnot. Did some workarounds on my iPad and it worked just fine.

**Comment by ThePickNick** [comment] 2019-08-23 22:23
there is an way for android device but u need a root and make a user certificate part of the system do OS would think its a system cert and it will automatically build trust. this article talks about it. I have not tested this but as soon as i get my android tablet im rooting it so I will post the results if it does anything. her is the link to article how they are doing it. if someone has a rooted device please try it

https://blog.nviso.be/2017/12/22/intercepting-https-traffic-from-apps-on-android-7-using-magisk-burp/

**Comment by Joching** [comment] 2019-08-24 03:09
Can't get it to work. I'm not very technical and the extra steps you mentioned went right over my head. I've been trying to get the thing to work for like an hour and a half until I saw this thread. I downloaded like 5 different versions of the app, restarted my computer and devices multiple times. Tried from different computers (Again had to download app again on other computer) and also tried from android and ios devices. I don't know, I probably didn't make the best decisions, but, I'm just tired and fed up, and just am counting on this issue to be fixed. Please, and thank you so much!

**Comment by darbyjack** [comment] 2019-08-24 03:12
> Can't get it to work. I'm not very technical and the extra steps you mentioned went right over my head. I've been trying to get the thing to work for like an hour and a half until I saw this thread. I downloaded like 5 different versions of the app, restarted my computer and devices multiple times. Tried from different computers (Again had to download app again on other computer) and also tried from android and ios devices. I don't know, I probably didn't make the best decisions, but, I'm just tired and fed up, and just am counting on this issue to be fixed. Please, and thank you so much!

Are you on Android or IOS?

**Comment by siwakorn9** [comment] 2019-08-24 03:16
Hi Gents

If you please kindly make a video for us that would be really helpful, no need to add your voice just step on video should do the job

Thanks

**Comment by KillerVibe** [comment] 2019-08-24 10:22
hey i installed the 0.27v also the ca.pam on my iphone i activated it throw the settings and still to internet connection to my iphone and cant go into summoenrs

**Comment by Pearcen33** [comment] 2019-08-25 10:19
So i can connect to the game server via proxy. but Log says still "Now listening on port 8080". Android

**Comment by Smeeth** [comment] 2019-08-26 09:03
neither version .27 nor .28 are working for me now. got the same logs like @Pearcen33.

on v.27: after installation ca.pem on android or ios there's no connection, availiable
on v.28: game loads and runs but no logs.

**Comment by duchoang** [comment] 2019-08-26 09:10
hey guys, pls read carefully all the replies above, here is tl;dr
- v0.28 does not work because of https
- v0.27 only works with ios + android low version (any version 7+ does not work unless rooting)

Have another question to @Xzandro: if I join your patreon to use this online proxy tool https://swex.swop.one, will this work for android 7+?

**Comment by Revark** [comment] 2019-08-26 12:35
"Have another question to @Xzandro: if I join your patreon to use this online proxy tool https://swex.swop.one, will this work for android 7+?"


Also curious about this.  I am patrón, but never used online exporter.  Just tried, can't get it to work, but might be an IP disconnect issue?

**Comment by Xzandro** [comment] 2019-08-26 13:09
No, SWEX Web isnt even updated yet. After I update it, there will be the same limitations, since these limitations are from the device itself.

**Comment by Xzandro** [comment] 2019-08-26 15:39
Yes. You would need to change the apk for that to make it work for Android 7+.

**Comment by Xzandro** [comment] 2019-08-26 15:55
Its still a user cert. The issue with Android7+ is that apps wont accept user certs by default. Its an easy fix on com2us end, but I doubt that they are interested in allowing user certs.

**Comment by Xzandro** [comment] 2019-08-26 16:25
Yes, thats what I meant with `install the user cert as a system cert`

**Comment by sik231** [comment] 2019-08-27 10:43
Hello everybody!  Here is a way anyone can export their JSON file using Nox player on PC (as of 8/27/19):

1. Download and install latest Nox player: https://www.bignox.com/blog/
2. Open Nox > System Settings ("gear" button on top right) > Click "Root" and restart
3. Download and install SW Exporter v0.0.27 > Open app and press "Get Cert"
4. Drag n drop "ca.pem" from exporter files folder to Nox player (anywhere in the home tab)
5. In Nox, Click "Tools" (on home page) > Settings > Security > Install from SD card
6. Choose "ca.pem," from where it saved to (mine saved to pictures), and name it ca.pem. It will ask for a pin and restart.
7. Now, click Tools > File Manager > data/misc/keystore/user_0/ and select the certificate you installed
8. Next, click "Parent Folder" (top) until you are back to the main directory and go to system/etc/security/cacerts
9. Click on the menu button on the top right (looks like traffic lights) and select "Move selection here"
10. Finally, click Settings > Wi-Fi > **_LONG PRESS_** WiredSSID > Modify network > Advanced options and put your Exporter ip address and port as normal

You are now ready to download and install SW in Nox and use the exporter to get your JSON file.  **_If you want to actually play using Nox, you will have to deselect root_**.  If you forget to deselect, it is not a big deal.  The game simply tells you to make sure root is deactivated before playing and force you to restart the app.  Also, after moving the certificate, you can clear the pin you made.

Without SWOP, SW is much harder to play imo.  So, thanks to Xzandro and everyone who make this app possible.  Hope this helps those having issues!  Cheers.

**Comment by Xagev** [comment] 2019-08-27 12:22
> Hello everybody! Here is a way anyone can export their JSON file using Nox player on PC (as of 8/27/19):
> 
> 1. Download and install latest Nox player: https://www.bignox.com/blog/
> 2. Open Nox > System Settings ("gear" button on top right) > Click "Root" and restart
> 3. Download and install SW Exporter v0.0.27 > Open app and press "Get Cert"
> 4. Drag n drop "ca.pem" from exporter files folder to Nox player (anywhere in the home tab)
> 5. In Nox, Click "Tools" (on home page) > Settings > Security > Install from SD card
> 6. Choose "ca.pem," from where it saved to (mine saved to pictures), and name it ca.pem. It will ask for a pin and restart.
> 7. Now, click Tools > File Manager > data/misc/keystore/user_0/ and select the certificate you installed
> 8. Next, click "Parent Folder" (top) until you are back to the main directory and go to system/etc/security/cacerts
> 9. Click on the menu button on the top right (looks like traffic lights) and select "Move selection here"
> 10. Finally, click Settings > Wi-Fi > **_LONG PRESS_** WiredSSID > Modify network > Advanced options and put your Exporter ip address and port as normal
> 
> You are now ready to download and install SW in Nox and use the exporter to get your JSON file. **_If you want to actually play using Nox, you will have to deselect root_**. If you forget to deselect, it is not a big deal. The game simply tells you to make sure root is deactivated before playing and force you to restart the app. Also, after moving the certificate, you can clear the pin you made.
> 
> Without SWOP, SW is much harder to play imo. So, thanks to Xzandro and everyone who make this app possible. Hope this helps those having issues! Cheers.

Great work. It works like a charm. 
Thanks a lot

**Comment by fnk93** [comment] 2019-08-27 19:18
@sik231: Nox is using Android 5. Therefore no need to root or move the certificate into the system-certificates-folder.
When I tested it, 5 days ago or something, all I needed to do was:
1. Your steps 1, 3, 4, 5 and 6.
2. After restart just your step 10 and then start Summoners war.

As mentioned above several times, every android device running Android lower than version 7 does not need root access, you can just install the certificate and it will be trusted.

**Comment by duchoang** [comment] 2019-08-27 21:42
Has anyone tried to use Nox on Mac, when I install and open SW first time, it displays this `Confirm age` box with this blank text and I cannot continue the game :(

![image](https://user-images.githubusercontent.com/3921326/63809897-5f332c80-c91b-11e9-8ecb-26be4c014f28.png)

**Comment by Xzandro** [comment] 2019-08-27 21:56
At this point. This doesnt really have to do anything with SWEX anymore. For general support you could join my [Discord server](https://discord.gg/JMBSZRA) or ask on reddit. Also read the reddit thread I did a few weeks ago [here](https://www.reddit.com/r/summonerswar/comments/cnwaq5/swex_0027_attempt_to_restore_export_functionality/).
@duchoang to answer your question still: try mobile phone resolution in the Nox settings.

I will release a new SWEX version within the next days to avoid confusion, that the last release doesn't work, We need to accept this situation, if you have any other solutions or bugs with SWEX, feel free to open a new issue. Closing this one.

**Closed by Xzandro** 2019-08-27 21:56 UTC

**Comment by siwakorn9** [comment] 2019-08-28 00:12
Well folk, Just for my curiosity.

Com2us used to say if you're using third party program ex. Nox on PC you will take your own risk to get ban.

Is this true ?

Thanks
