### ISSUE TITLE
Issue on iOS 13.1.2

### ISSUE THREAD

**Issue by Randy-M** [Xzandro/sw-exporter#290] opened 2019-10-09 05:30 UTC
Returning player, just attempting to get SWEX back up and running.

> I uninstalled & deleted all SWEX folders on my windows profile. 
> Installed release .30 & followed steps to install cert on my iPhone
> Cert installs properly, SWEX proxy is running, & my phone is properly connected to it

However despite all that I am not getting any log events in SWEX and no JSON data is downloaded/created on my computer. Seems like a possible issue with iOS 13.1.x since most comments I was reading were saying it was working.

**Comment by Dome5881** [comment] 2019-10-09 10:17
Having the same issue. 
It is working good for me on my iPad (iOS 12.4.1) but no longer works on my phone (iOS 13.1.2).
When opening summoners war i get a message saying network error and i am not able to connect.

**Comment by Xzandro** [comment] 2019-10-09 13:17
Duplicate of #283

**Closed by Xzandro** 2019-10-09 13:17 UTC
