### ISSUE TITLE
TypeError: port option should be a number or string: null

### ISSUE THREAD

**Issue by Gamewalker** [Xzandro/sw-exporter#128] opened 2018-03-29 00:59 UTC
Hello,

getting this exception like every 10 minutes and need to stop and start proxy.

https://suckmypic.net/9pfEraCu.png

**Comment by Xzandro** [comment] 2018-04-27 15:48
Duplicate of #74

**Closed by Xzandro** 2018-04-27 15:48 UTC

**Comment by Gamewalker** [comment] 2018-05-12 14:30
I changed my server completly and on a fresh Windows Server 2016 wothout any Antivirus/FW enabled or even installed it happens constantly.
