### ISSUE TITLE
Chinese servers can't get data with the latest version. What should we do now,

### ISSUE THREAD

**Issue by gangganab22** [Xzandro/sw-exporter#354] opened 2021-01-05 16:55 UTC
**Please don't report issues that are not relevant to SWEX. Especially now that are more steps involved which you can read on [reddit](https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/). To get more information, join the [Discord](https://discord.gg/JMBSZRA).**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Version

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Xzandro** [comment] 2021-01-05 20:24
Duplicate of #353

**Closed by Xzandro** 2021-01-05 20:24 UTC
