### ISSUE TITLE
Summoners war Exporter

### ISSUE THREAD

**Issue by kayak13500** [Xzandro/sw-exporter#192] opened 2019-02-01 08:22 UTC
Bonjour 
Quand je lance Summoners War Exporter je reçois le message suivant:

ErrorPlugin - SwarfarmLogger 09:00:52
Unable to retrieve accepted log types. SWARFARM logging is disabled.
Cordialement

**Comment by PeteAndersen** [comment] 2019-02-01 14:37
This will be resolved in 1 week approximately - data logging is currently disabled on SWARFARM

**Comment by Xzandro** [comment] 2019-02-01 15:21
Not a bug with SWEX. Closing.

**Closed by Xzandro** 2019-02-01 15:21 UTC

**Comment by Naxtra** [comment] 2019-02-11 21:24
Even though it isn't a SWEX bug, how do I fix it? I still have this issue.

**Comment by Xzandro** [comment] 2019-02-11 21:36
You can't. Data logging on SWARFARM just isnt enabled yet. If you dont wanna see this emssage, disable the SwarfarmPlugin. Other thanthat, this has no influence on the corte functionality of SWEX.

**Comment by Naxtra** [comment] 2019-02-11 21:38
Ahh, well I don't mind the SWARFARM, I just thought that the error was the reason that my proxy isn't working anymore. I have no idea why, I used the exporter before without a problem.
