### ISSUE TITLE
Not exporting

### ISSUE THREAD

**Issue by wickedchett** [Xzandro/sw-exporter#244] opened 2019-08-21 09:16 UTC
Not sure why its not grabbing anything. I'm on the same wifi network as my phone and desktop listed and tried both bands. Even changed the port number just in case something else was using it like some suggested. I've also disabled the firewall and virus scanner, but still can't get it to work.
My only thought it is it has something to do with my router. It's a TP-Link Archer A7 if that helps.

**Comment by ianchudson** [comment] 2019-08-21 10:18
Duplicate of 243. Com2us is using HTTPS again which requires a different SWEX.

**Comment by Xzandro** [comment] 2019-08-21 13:18
Duplicate of #243, closing.

**Closed by Xzandro** 2019-08-21 13:18 UTC
