### ISSUE TITLE
Cant log in to summoners war after changing my http proxy to manual

### ISSUE THREAD

**Issue by dmz97** [Xzandro/sw-exporter#328] opened 2020-07-07 16:43 UTC

**Comment by Xzandro** [comment] 2020-07-07 18:23
Closing, since there was no information provided to work with. And since this is probably not a bug in SWEX itself. As a tip: disable the HTTPS mode option in the SWEX settings and follow the steps in the Help section within SWEX.

**Closed by Xzandro** 2020-07-07 18:23 UTC
