### ISSUE TITLE
[BUG] [0.0.37] [Mac] [BigSur] No data exported

### ISSUE THREAD

**Issue by tunglt1810** [Xzandro/sw-exporter#377] opened 2021-02-17 04:40 UTC
I download the latest release version for Mac. My OS is Big Sur. So the proxy can start but no data exported. I checked all log options but no data event collected.
And when i close the window, there is a bug popup

![image](https://user-images.githubusercontent.com/19906349/108157268-e7f7e680-7114-11eb-8c37-3230540a800f.png)

**Comment by Xzandro** [comment] 2021-02-17 05:22
The error message is a valid bug. That no data is exported is not. Since people can't really stay on topic currently, because they don't understand why additional steps are now required, I will close this issue.

Regarding the full-logger bug I will create a separate issue.

Duplicate of #359

**Closed by Xzandro** 2021-02-17 05:22 UTC
