### ISSUE TITLE
[BUG] iPhone connects through proxy but SWEX does not write JSON

### ISSUE THREAD

**Issue by stratejem** [Xzandro/sw-exporter#425] opened 2021-11-18 21:47 UTC
**Please don't report issues that are not relevant to SWEX. Especially now that are more steps involved which you can read on [reddit](https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/). To get more information, join the [Discord](https://discord.gg/JMBSZRA).**

**Describe the bug**
So, today I was having issue exporting the JSON.

Regenerated cert

Got new certificate

Transferred to phone

Installed cert and made sure to set it to full access

Have HTTPS on

Couldn't get it to work either on a Windows 10 PC nor a Macbook Pro. I'm using an iPhone 13 Pro with iOS 15.1. I know that the phone is connected through the proxy because game has network errors when I stop the proxy. Also game just black screens with failure to connect if I disable HTTPS.

Also tried all the above steps with an iPad, but same result.

Quite puzzled as it was just working on the 31st of November. Anyone else having issues?

Does anyone have a solution?

Thanks!

**To Reproduce**

I supposed it was reproduced because it didn't work no matter what system/device I tried.

**Expected behavior**
Expected SWEX to write JSON as game was successfully connected through proxy.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Win10, MacOS Monterey
- Version: Both with latest updates

**Smartphone (please complete the following information):**

- Device: iPhone 13 Pro/iPad Pro 2018
- OS: iOS, iPadOS

**Additional context**
As above.

**Comment by Xzandro** [comment] 2021-11-19 04:43
Enable HTTPS mode and also do all the other required certs. Make sure to instrall the cert AND enable root for that cert. See here for example: https://www.reddit.com/r/summonerswar/comments/l43ueg/making_swex_work_in_2021/ Duplicate of #359

**Closed by Xzandro** 2021-11-19 04:43 UTC
