### ISSUE TITLE
A JavaScript error occured in the main process

### ISSUE THREAD

**Issue by Cptkrawall** [Xzandro/sw-exporter#340] opened 2020-11-01 21:25 UTC
Hello together,

i have been using the SW exporter for some time now and never had any problems. since last night i have the following problem.Look at the picture below. After some research i did not find a solution. But I tried the usual: reinstall, reboot my PC, update java and search for updates in Windows. but nothing helped. do you know a solution?

best regards

![SW Exporter Error](https://user-images.githubusercontent.com/73798419/97815713-5319cc00-1c90-11eb-911f-62cd77a9b4ca.jpg)

**Comment by Xzandro** [comment] 2020-11-01 21:39
Duplicate of #339

**Closed by Xzandro** 2020-11-01 21:39 UTC
