### ISSUE TITLE
Recolting data issue

### ISSUE THREAD

**Issue by DripPick** [Xzandro/sw-exporter#249] opened 2019-08-23 19:17 UTC
Hi, 
I use an IPhone X and a msi computer under Windows 10 and a mac air,both failed to collect my data. I am sure i have well entered the proxy adress AND i shut down all the fire Wall on my computer but when i start my game while beign connected to the proxy,the game is lauching normally (i can play as usual) but there is nothing happening on the SW exporter,only « listening to proxy » is written.
Do you have any solution ? I am running the 0.28 version
Thanks and best regards 
Someone who really wants to use you app, aka DripPick

**Comment by oblivion2859** [comment] 2019-08-23 19:27
i can confirm having the same issue

**Comment by PeteAndersen** [comment] 2019-08-23 20:21
Duplicate of #243. Please check that issue thread

**Closed by PeteAndersen** 2019-08-23 20:21 UTC
