### ISSUE TITLE
ios 13 update, SWEX not working now [BUG]

### ISSUE THREAD

**Issue by ios-user-1-2-3** [Xzandro/sw-exporter#291] opened 2019-10-12 15:27 UTC
after updating to ios 13, SWEX is no longer working.  Error states failed to connect with the network.  Attempted to reinstall the cert and swex, still received the same error.

**Comment by Xzandro** [comment] 2019-10-12 15:41
It is still working.
Duplicate of #283

**Closed by Xzandro** 2019-10-12 15:41 UTC

**Comment by ios-user-1-2-3** [comment] 2019-10-12 19:34
Remember to do the certificate trust settings radio button after installing the new pem file to iOS
