### ISSUE TITLE
Can't even open the game

### ISSUE THREAD

**Issue by Molegz** [Xzandro/sw-exporter#258] opened 2019-08-29 03:57 UTC
After I can't use the SWProxy anymore, I've tried to use the SWExporter, but when I try to open the game it shows this instantly:

![Screenshot_2019-08-29-00-51-17](https://user-images.githubusercontent.com/54656014/63908905-3718fb80-c9f7-11e9-9874-3b23e76057aa.png)

I already saw any kind of error of my own, but I did everything right... I opened the program, started proxy, allowed my firewall to any type of network, putted the right IP and the right port, but I always get the same problem! If you have any type of solution or any help for me I will be very glad...

**Comment by Gaalee** [comment] 2019-08-29 04:13
Same error here, probably because of the new update. Hope it get fixed to be able to benefit from those 3 days FRR !

**Comment by agntorg** [comment] 2019-08-29 05:43
Same...

**Comment by smcdonald45** [comment] 2019-08-29 06:45
I also cant login anymore. I also added the cert (https://www.reddit.com/r/summonerswar/comments/cnwaq5/swex_0027_attempt_to_restore_export_functionality/).

**Comment by Xzandro** [comment] 2019-08-29 11:51
SWEX works just fine with the limitations stated in the reources.
Duplicate of #243

**Closed by Xzandro** 2019-08-29 11:51 UTC
