### ISSUE TITLE
Android users exporter not working

### ISSUE THREAD

**Issue by ThePickNick** [Xzandro/sw-exporter#247] opened 2019-08-22 19:48 UTC
I have and android version 8.0+ it seems like exporter v 0.28 not working for me. I set up everything start up the proxy and fire up sw but noting is being exported I was able to login into sw just fine but .json file is not being created does anyone have similar issue ? 

Also I enabled everything logging related but noting is showing in the log  besides proxy started 
![Capture](https://user-images.githubusercontent.com/16995566/63545295-0f0c3280-c4f5-11e9-97fc-0b79f8a8d46c.PNG)
![Capture2](https://user-images.githubusercontent.com/16995566/63545339-23e8c600-c4f5-11e9-9fa3-9552c32f7ccc.PNG)

**Comment by pagough** [comment] 2019-08-22 20:22
I'm getting the same. Is this the same https issue?

**Comment by Sunoyr** [comment] 2019-08-22 21:36
Same issue for me :(

**Comment by Xzandro** [comment] 2019-08-22 21:49
Duplicate of #243

**Closed by Xzandro** 2019-08-22 21:49 UTC
