### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by WulffeSilvermane** [Xzandro/sw-exporter#387] opened 2021-04-29 12:31 UTC
**Please don't report issues that are not relevant to SWEX. Especially now that are more steps involved which you can read on [reddit](https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/). To get more information, join the [Discord](https://discord.gg/JMBSZRA).**

**Describe the bug**
I have followed the posted instructions for Nox, Bluestacks and Iphone and none of them seem to produce a .json file.  I am connecting through the proxy but the file is not being generated.

**Comment by Xzandro** [comment] 2021-04-29 14:46
Duplicate of #359

**Closed by Xzandro** 2021-04-29 14:46 UTC
