### ISSUE TITLE
Json File not being pulled

### ISSUE THREAD

**Issue by ikonkeru** [Xzandro/sw-exporter#367] opened 2021-01-22 03:47 UTC
I don't know when this happened but exporter is not working the proxy is on but no json file is pulled when the game starts. If I turn proxy off game doesn't load so I know proxy is working. Did the new update change something? My last download of my file was on 1/3/2021 and it worked as usual then.

Thanks for any advice on how to get it working again.

**Comment by Xzandro** [comment] 2021-01-22 03:53
Duplicate of #359

**Closed by Xzandro** 2021-01-22 03:53 UTC
