### ISSUE TITLE
[BUG] SWEX not working

### ISSUE THREAD

**Issue by joeccyin** [Xzandro/sw-exporter#284] opened 2019-09-29 14:49 UTC
I'm using iOS 13.1, iPhone 6s, iPhone XS and iPad also not working.

**Comment by BadUncle23** [comment] 2019-09-29 16:58
I can confirm it no longer works on the new Ipad OS.

**Comment by joeccyin** [comment] 2019-09-29 17:01
Thank you for you reply!

It work prefect last month, I will use android device to try tomorrow, hope
it can work on new iOS later.

Kind regards,
Joe

「BadUncle23 <notifications@github.com>」在 2019年9月30日 週一，上午12:58 寫道：

**Comment by Xzandro** [comment] 2019-09-30 01:01
Duplicate of #283

**Closed by Xzandro** 2019-09-30 01:01 UTC
