### ISSUE TITLE
Doesn't Work After Update

### ISSUE THREAD

**Issue by Navies911007** [Xzandro/sw-exporter#369] opened 2021-01-24 17:31 UTC
I used the exporter about a year ago and did it successfully several times, but then all of sudden it stopped working. I would setup the proxy and everything per usual, but it would not parse the data. The game just started up per usual and the proxy continues to listen without ever creating a json file. A few months ago, on a new laptop, I downloaded the 0.36 version and it worked successfully for months, but then today it did the same thing as a year ago...it just won't parse the data. I updated to the 0.37 version thinking that maybe the old version would not work once the updates came out, but this doesn't seem to solve the problem either. I've uninstalled and reinstalled several times and restarted both devices with no luck. Is there anything I can do to remedy this problem?

**Comment by Xzandro** [comment] 2021-01-24 17:56
Duplicate of #359

**Closed by Xzandro** 2021-01-24 17:56 UTC
