### ISSUE TITLE
Data is not captured

### ISSUE THREAD

**Issue by Speedo2k** [Xzandro/sw-exporter#375] opened 2021-02-06 16:30 UTC
I configure SWPE and see that it is working. When I stop proxy, then have no access to internet to SW and to other web pages. When I start proxy everything works find but there is no data collected from SW. Test many times with/without https option. With version 36 and 37 and I do not know how to make it working.

**Comment by Speedo2k** [comment] 2021-02-06 17:48
I found resolution on: https://www.reddit.com/r/summonerswar/comments/cnwaq5/swex_0027_attempt_to_restore_export_functionality/ewedxpi/

I installed com2us  certificate on IoS and everything is working fine.

Please close the ticket.

**Comment by Xzandro** [comment] 2021-02-06 19:59
Duplicate of #359

**Closed by Xzandro** 2021-02-06 19:59 UTC
