### ISSUE TITLE
SWExporter not working after last patch

### ISSUE THREAD

**Issue by Zenidog8** [Xzandro/sw-exporter#205] opened 2019-04-02 02:54 UTC
I have a galaxy s9 and run the software on ubuntu 18.04, but the proxy is not catching the data, it seems like the game is not using the proxy since last patch

**Comment by Xzandro** [comment] 2019-04-02 14:10
Tried it, this is working just fine for me still.

**Comment by addzam** [comment] 2019-04-02 19:33
I Second this, also having problems with it. been trying for hours, even following multiple guides and it wont catch the data.

**Comment by ganarajpr** [comment] 2019-04-03 11:17
Same issue. I am not able to get the proxy to log 'saved xxx.json' - I am not sure where the problem lies. Have been using the proxy with my phone for almost an year. 
swproxy version 0.0.24

**Comment by Xzandro** [comment] 2019-04-03 13:04
Still can't reproduce this. There was no change from com2us, neither from us. Make sure you allowed SWEX in your firewall and make sure to double-check IP and port.

**Comment by PeteAndersen** [comment] 2019-04-03 13:48
I am also unable to reproduce this, still working fine for me across 2 computers

**Comment by Marceloas89** [comment] 2019-04-03 15:39
Hi, i'm having that problem too, recently bought a galaxy s9 and not able to get the proxy. Checked the firewall and SWEX is allowed. Then i changed de port in SWEX to 8081, saved the configs in the phone, disabled and enabled the wifi again, started the SWEX and worked for me (Sorry for bad english)

**Comment by PeteAndersen** [comment] 2019-04-03 16:13
I see Galaxy S9 mentioned twice - @addzam do you also have a Galaxy S9? I am using a Pixel 2.

**Comment by ganarajpr** [comment] 2019-04-05 07:21
@Xzandro @PeteAndersen apparently the solution is to turn off the wifi and turn it back on - before attempting to connect with the proxy / opening the sw game. 

https://www.reddit.com/r/summonerswar/comments/b9cjtl/swop_53_rune_statistics/ek470kf?utm_source=share&utm_medium=web2x

**Comment by PeteAndersen** [comment] 2019-04-05 17:34
Thanks! Seems like it's a phone issue so I'll close this here.

**Closed by PeteAndersen** 2019-04-05 17:34 UTC
