### ISSUE TITLE
Not Download files

### ISSUE THREAD

**Issue by Zekarlo73** [Xzandro/sw-exporter#383] opened 2021-03-28 17:29 UTC
Hello i have a problem, I have always used the application without problems but today after activating the certificate and configuring the proxy data, it is left with the message "listening to port 8080" but it does not download the data when opening summoners war, I already happened once and I solved it by reinstalling the certificate but this time it has not worked it may be a problem of the last updates of the game.
I use an Ipad with the latest version of iOS and versión 0.0.37 of exporter

**Comment by Xzandro** [comment] 2021-03-28 20:33
Well, did you enable HTTPS mode in the SWEX settings?

**Comment by crazysheep19** [comment] 2021-03-28 21:44
> 
> 
> Well, did you enable HTTPS mode in the SWEX settings?

i have not and i have the same problem. Proxy is running. Also summoners war is running. but json/myprofile isnt loading in the sw exporter. it only says listening on port 8080 and it also say looking for the following commands to sync with your profile: Hubuserlogin......like 20 of them. Can u help me?

**Comment by Xzandro** [comment] 2021-03-28 23:35
As suspected.

Duplicate of #359

**Closed by Xzandro** 2021-03-28 23:35 UTC

**Comment by Zekarlo73** [comment] 2021-03-29 08:42
It was unmarked thanks I have marked it and it has already worked again
