### ISSUE TITLE
[BUG] JSON file not being created

### ISSUE THREAD

**Issue by STFUppercut** [Xzandro/sw-exporter#376] opened 2021-02-15 18:39 UTC
**Please don't report issues that are not relevant to SWEX. Especially now that are more steps involved which you can read on [reddit](https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/). To get more information, join the [Discord](https://discord.gg/JMBSZRA).**

**Describe the bug**
I have been able to create a proxy through the SWEX app and successfully log into my SW account through the proxy. Same process I have done recently in Nov. This time the JSON file for me to upload into the optimizer is being created.

**To Reproduce**

1. Start Proxy on SWEX app
2. Direct WiFi settings to proxy
3. Start SW on Nox
4. Wait for SW to load but no JSON

**Expected behavior**
JSON file to be created

**Screenshots**

**Desktop (please complete the following information):**

- Version

**Smartphone (please complete the following information):**

- Device: Nox Android 5 emulator

**Additional context**

**Comment by Xzandro** [comment] 2021-02-15 18:51
Duplicate of #359

**Closed by Xzandro** 2021-02-15 18:51 UTC
