### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by DamienStylez** [Xzandro/sw-exporter#230] opened 2019-07-24 11:53 UTC
How should I setup the proxy when Android 9 doesnt support / doesnt save proxy settings?

**Comment by DamienStylez** [comment] 2019-07-24 11:55
Edit: https://www.reddit.com/r/summonerswar/comments/ba21pf/swex_not_working_in_android_9/
THis is basically the only fixation atm - if anyone else had the same problem as i had.

**Comment by PeteAndersen** [comment] 2019-07-24 15:03
Duplicate of #255

**Closed by PeteAndersen** 2019-07-24 15:03 UTC
