### ISSUE TITLE
Failed Connection 

### ISSUE THREAD

**Issue by Locdogh** [Xzandro/sw-exporter#262] opened 2019-08-29 14:18 UTC
Hi

I downloaded the lastest version but i can't connect on my game

"Failed to connect with the netwprk. Please try again"

But i have net connection with google or facebook or other ..

I have desactivated my firewall and i m sure for adress Ip and port .

I have tested different port but always same text in my game 

Sorry for my bad english

**Comment by Xzandro** [comment] 2019-08-29 14:21
Duplicate of #243

**Closed by Xzandro** 2019-08-29 14:21 UTC
