### ISSUE TITLE
Wif [BUG]

### ISSUE THREAD

**Issue by SWmakesmemad** [Xzandro/sw-exporter#395] opened 2021-06-16 20:02 UTC
Hi, 

I have been trying to sw rune optimizer to work.

I get to the part of the proxy and two issues occur. 1. wifi stops working with the proxy on. 2. no json file is created i have looked every where and I only get more angry.. Help me please

**Comment by Xzandro** [comment] 2021-06-16 21:59
Duplicate of #359

**Closed by Xzandro** 2021-06-16 21:59 UTC
