### ISSUE TITLE
[BUG] "Failed to connect with the network. Please try again later." message on HTTPS and iOS 14.4

### ISSUE THREAD

**Issue by andy-ju** [Xzandro/sw-exporter#371] opened 2021-02-03 19:14 UTC
**Please don't report issues that are not relevant to SWEX. Especially now that are more steps involved which you can read on [reddit](https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/). To get more information, join the [Discord](https://discord.gg/JMBSZRA).**

**Describe the bug**

After Com2us changed the connection protocol to HTTPS and upgraded iOS from 14.3 to 14.4,
when starting Summoners War app, it says like "Failed to connect with the network. Please try again later." and couldn't proceed.
In that case, SWEX is running as HTTPS mode.

**To Reproduce**

**Expected behavior**

Summoners War app starts without errors and SWEX intercepts the packet and export the profile file.

**Screenshots**
![SWEP](https://user-images.githubusercontent.com/13800799/106796405-a2600600-669e-11eb-8e03-85560641fda3.PNG)
![App](https://user-images.githubusercontent.com/13800799/106796626-f2d76380-669e-11eb-877e-a365fc64d335.png)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Windows 10 Education 
- Version : 20H2 Build 19042.746

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6] iPhone 11
- OS: [e.g. iOS8.1]  iOS 14.4

**Additional context**

I don't know which one is causing the problem.
- Com2us changed the connection protocol to HTTPS
- iOS upgrade from 14.3 to 14.4
- Something else I don't recognize

**Comment by darkvidious** [comment] 2021-02-04 00:29
Same here

**Comment by Xzandro** [comment] 2021-02-04 01:27
I dont see any meaningful changes in iOS 14.4, that would influence anything regarding SWEX. It's probably because of HTTPS. I will close this issue as well, since people will just abuse the issue to state that it does not work anymore without reading the changes and additional steps it now requires with HTTPS. Sadly, it's really hard to discuss any errors regarding this topic. 

Duplicate of #359

**Closed by Xzandro** 2021-02-04 01:27 UTC
