### ISSUE TITLE
Exporter w'on't save json files 

### ISSUE THREAD

**Issue by ozozozoz9** [Xzandro/sw-exporter#385] opened 2021-04-23 08:48 UTC
Hi,

I've been using SWEX for a while now, I just bought a new computer and downloaded it again. Everytime I start the proxy and logging into the account It looks like the account doesn't register with the proxy and won't run "through" the exporter it will run like as I open the game without anything. I have rules and the firewall allow the exporter to work but I just don't know why it won't register in the proxy.

Any help will be accepted gladly :)

**Comment by iAmJay-Tee** [comment] 2021-04-23 11:40
Have you enabled the https option in SWEX ?

**Comment by ozozozoz9** [comment] 2021-04-23 16:35
Yes I tried doing so but it wont be able to log into the game because it will say that I have no internet connection

**Comment by iAmJay-Tee** [comment] 2021-04-24 14:49
Then we got the same issue :(
From what i understood running trough reddit and youtube tutorials, in any case you must enable the https mode for SWEX to work since Com2us sends their JSON via https.
The question is, what causes the "Cannot reach network, try again later error" when the https mode is enabled?

**Comment by Xzandro** [comment] 2021-04-24 14:57
You need additional steps to install the cert etc.. This isnt really a great platform to help with general usability and stuff tho.

Duplicate of #359

**Closed by Xzandro** 2021-04-24 14:57 UTC
